version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      # Unfortunately currently CodePipeline does not retain file permissions
      # during actions/phases. So make the gradlew script executable maually
      - chmod +x ./gradlew
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew fatJar
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/load_sandmann-all-1.0.jar
